// flow-typed signature: 16c70b6e1a27de2ca43deae34e7c996a
// flow-typed version: <<STUB>>/babel-plugin-universal-import_v^3.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-universal-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-universal-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-universal-import/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'babel-plugin-universal-import/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'babel-plugin-universal-import/universalImport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-universal-import/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'babel-plugin-universal-import/coverage/lcov-report/prettify'>;
}
declare module 'babel-plugin-universal-import/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'babel-plugin-universal-import/coverage/lcov-report/sorter'>;
}
declare module 'babel-plugin-universal-import/index' {
  declare module.exports: $Exports<'babel-plugin-universal-import'>;
}
declare module 'babel-plugin-universal-import/index.js' {
  declare module.exports: $Exports<'babel-plugin-universal-import'>;
}
declare module 'babel-plugin-universal-import/universalImport.js' {
  declare module.exports: $Exports<'babel-plugin-universal-import/universalImport'>;
}
