// flow-typed signature: 0c51ba7db66b4cef8538da2e352b5ccf
// flow-typed version: <<STUB>>/extract-css-chunks-webpack-plugin_v^3.0.11/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-css-chunks-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-css-chunks-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-css-chunks-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'extract-css-chunks-webpack-plugin/dist/hotLoader' {
  declare module.exports: any;
}

declare module 'extract-css-chunks-webpack-plugin/dist/hotModuleReplacement' {
  declare module.exports: any;
}

declare module 'extract-css-chunks-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'extract-css-chunks-webpack-plugin/dist/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-css-chunks-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'extract-css-chunks-webpack-plugin/dist/cjs'>;
}
declare module 'extract-css-chunks-webpack-plugin/dist/hotLoader.js' {
  declare module.exports: $Exports<'extract-css-chunks-webpack-plugin/dist/hotLoader'>;
}
declare module 'extract-css-chunks-webpack-plugin/dist/hotModuleReplacement.js' {
  declare module.exports: $Exports<'extract-css-chunks-webpack-plugin/dist/hotModuleReplacement'>;
}
declare module 'extract-css-chunks-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'extract-css-chunks-webpack-plugin/dist/index'>;
}
declare module 'extract-css-chunks-webpack-plugin/dist/loader.js' {
  declare module.exports: $Exports<'extract-css-chunks-webpack-plugin/dist/loader'>;
}
