// flow-typed signature: d914b67958e25c32767caf2645e8da5c
// flow-typed version: <<STUB>>/stylelint-declaration-strict-value_v^1.0.4/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-declaration-strict-value'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-declaration-strict-value' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-declaration-strict-value/defaults' {
  declare module.exports: any;
}

declare module 'stylelint-declaration-strict-value/lib/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-declaration-strict-value/defaults.js' {
  declare module.exports: $Exports<'stylelint-declaration-strict-value/defaults'>;
}
declare module 'stylelint-declaration-strict-value/index' {
  declare module.exports: $Exports<'stylelint-declaration-strict-value'>;
}
declare module 'stylelint-declaration-strict-value/index.js' {
  declare module.exports: $Exports<'stylelint-declaration-strict-value'>;
}
declare module 'stylelint-declaration-strict-value/lib/validation.js' {
  declare module.exports: $Exports<'stylelint-declaration-strict-value/lib/validation'>;
}
