// flow-typed signature: ba7db9b7afa62fe1c2c4f26cf78b42ff
// flow-typed version: <<STUB>>/stylelint-declaration-block-no-ignored-properties_v^1.1.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-declaration-block-no-ignored-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-declaration-block-no-ignored-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-declaration-block-no-ignored-properties/utils/matchesStringOrRegExp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-declaration-block-no-ignored-properties/index' {
  declare module.exports: $Exports<'stylelint-declaration-block-no-ignored-properties'>;
}
declare module 'stylelint-declaration-block-no-ignored-properties/index.js' {
  declare module.exports: $Exports<'stylelint-declaration-block-no-ignored-properties'>;
}
declare module 'stylelint-declaration-block-no-ignored-properties/utils/matchesStringOrRegExp.js' {
  declare module.exports: $Exports<
    'stylelint-declaration-block-no-ignored-properties/utils/matchesStringOrRegExp',
  >;
}
