// flow-typed signature: 044eb82ed3bc6b396816c8cf31aede46
// flow-typed version: <<STUB>>/@storybook/addon-backgrounds_v^3.4.8/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-backgrounds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-backgrounds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-backgrounds/dist/BackgroundPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/Swatch' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/__tests__/BackgroundPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/__tests__/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/__tests__/Swatch' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/BackgroundPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/src/Swatch' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-backgrounds/dist/BackgroundPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/BackgroundPanel'>;
}
declare module '@storybook/addon-backgrounds/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/index'>;
}
declare module '@storybook/addon-backgrounds/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/register'>;
}
declare module '@storybook/addon-backgrounds/dist/Swatch.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/Swatch'>;
}
declare module '@storybook/addon-backgrounds/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/register'>;
}
declare module '@storybook/addon-backgrounds/src/__tests__/BackgroundPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/__tests__/BackgroundPanel'>;
}
declare module '@storybook/addon-backgrounds/src/__tests__/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/__tests__/index'>;
}
declare module '@storybook/addon-backgrounds/src/__tests__/Swatch.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/__tests__/Swatch'>;
}
declare module '@storybook/addon-backgrounds/src/BackgroundPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/BackgroundPanel'>;
}
declare module '@storybook/addon-backgrounds/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/index'>;
}
declare module '@storybook/addon-backgrounds/src/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/register'>;
}
declare module '@storybook/addon-backgrounds/src/Swatch.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/src/Swatch'>;
}
