// flow-typed signature: 619d28fcfb7f668fc0cd39792e8d59db
// flow-typed version: <<STUB>>/@storybook/react_v^4.0.0-alpha.14/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react/bin/build' {
  declare module.exports: any;
}

declare module '@storybook/react/bin/index' {
  declare module.exports: any;
}

declare module '@storybook/react/demo' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/client/index' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/client/preview/element_check' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/client/preview/globals' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/client/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/client/preview/render' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/demo/Button' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/demo/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/build' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/index' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/options' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/wrapBabelConfig' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/wrapDefaultBabelConfig' {
  declare module.exports: any;
}

declare module '@storybook/react/src/client/index' {
  declare module.exports: any;
}

declare module '@storybook/react/src/client/preview/element_check' {
  declare module.exports: any;
}

declare module '@storybook/react/src/client/preview/element_check.test' {
  declare module.exports: any;
}

declare module '@storybook/react/src/client/preview/globals' {
  declare module.exports: any;
}

declare module '@storybook/react/src/client/preview/index' {
  declare module.exports: any;
}

declare module '@storybook/react/src/client/preview/render' {
  declare module.exports: any;
}

declare module '@storybook/react/src/demo/Button' {
  declare module.exports: any;
}

declare module '@storybook/react/src/demo/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/react/src/server/build' {
  declare module.exports: any;
}

declare module '@storybook/react/src/server/index' {
  declare module.exports: any;
}

declare module '@storybook/react/src/server/options' {
  declare module.exports: any;
}

declare module '@storybook/react/src/server/wrapBabelConfig' {
  declare module.exports: any;
}

declare module '@storybook/react/src/server/wrapBabelConfig.test' {
  declare module.exports: any;
}

declare module '@storybook/react/src/server/wrapDefaultBabelConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/react/bin/build.js' {
  declare module.exports: $Exports<'@storybook/react/bin/build'>;
}
declare module '@storybook/react/bin/index.js' {
  declare module.exports: $Exports<'@storybook/react/bin/index'>;
}
declare module '@storybook/react/demo.js' {
  declare module.exports: $Exports<'@storybook/react/demo'>;
}
declare module '@storybook/react/dist/client/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/client/index'>;
}
declare module '@storybook/react/dist/client/preview/element_check.js' {
  declare module.exports: $Exports<'@storybook/react/dist/client/preview/element_check'>;
}
declare module '@storybook/react/dist/client/preview/globals.js' {
  declare module.exports: $Exports<'@storybook/react/dist/client/preview/globals'>;
}
declare module '@storybook/react/dist/client/preview/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/client/preview/index'>;
}
declare module '@storybook/react/dist/client/preview/render.js' {
  declare module.exports: $Exports<'@storybook/react/dist/client/preview/render'>;
}
declare module '@storybook/react/dist/demo/Button.js' {
  declare module.exports: $Exports<'@storybook/react/dist/demo/Button'>;
}
declare module '@storybook/react/dist/demo/Welcome.js' {
  declare module.exports: $Exports<'@storybook/react/dist/demo/Welcome'>;
}
declare module '@storybook/react/dist/server/build.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/build'>;
}
declare module '@storybook/react/dist/server/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/index'>;
}
declare module '@storybook/react/dist/server/options.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/options'>;
}
declare module '@storybook/react/dist/server/wrapBabelConfig.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/wrapBabelConfig'>;
}
declare module '@storybook/react/dist/server/wrapDefaultBabelConfig.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/wrapDefaultBabelConfig'>;
}
declare module '@storybook/react/src/client/index.js' {
  declare module.exports: $Exports<'@storybook/react/src/client/index'>;
}
declare module '@storybook/react/src/client/preview/element_check.js' {
  declare module.exports: $Exports<'@storybook/react/src/client/preview/element_check'>;
}
declare module '@storybook/react/src/client/preview/element_check.test.js' {
  declare module.exports: $Exports<'@storybook/react/src/client/preview/element_check.test'>;
}
declare module '@storybook/react/src/client/preview/globals.js' {
  declare module.exports: $Exports<'@storybook/react/src/client/preview/globals'>;
}
declare module '@storybook/react/src/client/preview/index.js' {
  declare module.exports: $Exports<'@storybook/react/src/client/preview/index'>;
}
declare module '@storybook/react/src/client/preview/render.js' {
  declare module.exports: $Exports<'@storybook/react/src/client/preview/render'>;
}
declare module '@storybook/react/src/demo/Button.js' {
  declare module.exports: $Exports<'@storybook/react/src/demo/Button'>;
}
declare module '@storybook/react/src/demo/Welcome.js' {
  declare module.exports: $Exports<'@storybook/react/src/demo/Welcome'>;
}
declare module '@storybook/react/src/server/build.js' {
  declare module.exports: $Exports<'@storybook/react/src/server/build'>;
}
declare module '@storybook/react/src/server/index.js' {
  declare module.exports: $Exports<'@storybook/react/src/server/index'>;
}
declare module '@storybook/react/src/server/options.js' {
  declare module.exports: $Exports<'@storybook/react/src/server/options'>;
}
declare module '@storybook/react/src/server/wrapBabelConfig.js' {
  declare module.exports: $Exports<'@storybook/react/src/server/wrapBabelConfig'>;
}
declare module '@storybook/react/src/server/wrapBabelConfig.test.js' {
  declare module.exports: $Exports<'@storybook/react/src/server/wrapBabelConfig.test'>;
}
declare module '@storybook/react/src/server/wrapDefaultBabelConfig.js' {
  declare module.exports: $Exports<'@storybook/react/src/server/wrapDefaultBabelConfig'>;
}
